### PR TITLE
Don't suppress psiClass-prefix/suffix application for coincidentally matching rule names

### PR DESCRIPTION
**Pull request by calexHG**
*ahem*-- some of us are working on way more c00ler languages w/ single-letter names :P

### CODE REVIEW

**Comment by calexHG** [comment]
This adresses issue #123

**Comment by gregsh** [comment]
This PR generally deprecates "enforce" method, so I had to take care of that manually.

**Comment by calexHG** [comment]
lol, yeah... it kinda does.

d'oh.. I wanted another commit— I even mimicked your tendency towards insanely long, deeply nested ternary operations!

:facepunch:

**Comment by gregsh** [comment]
I'm so tired of scrolling multi-page java classes with trivial 'if-null-else' logic
so I just hide it in one-liners which nobody should read.
Eventually you'll understand me :-)

**Comment by gregsh** [comment]
> Welcome to the single-letter team :p

Greetings! I'm also employing meta with recoverWhile parameter from #100 there.

**Comment by calexHG** [comment]
Aaaah, nifty. I just got to check that out just now. I'm glad it was
useful. :)

Within the next few days, I expect to be sending you a very important
e-mail regarding the mysterious project I'm working on. Keep an eye out for
it, ok?

On Aug 12, 2016 1:40 PM, "Greg Shrago" <notifications@github.com> wrote:

Welcome to the single-letter team :p

Greetings! I'm also employing meta with recoverWhile parameter from #100
<https://github.com/JetBrains/Grammar-Kit/issues/100> there.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/JetBrains/Grammar-Kit/pull/122#issuecomment-239511852>,
or mute the thread

**Pull request closed without merging**
