### PR TITLE
Inject regexp language into 'regexp:' string literals

### PR DESCRIPTION
**Pull request by VladRassokhin**

### CODE REVIEW

**Comment by ArtsiomCh** [comment]
@gregsh please have a look. Really useful addition. Why it still pending?
PS When I test it, had to move `BnfRegexpInjector.java` from `support/org/intellij/grammar/editor/` to `org/intellij/grammar/editor/` and everything works. Despite that small fix, this PR could be easy merged.

**Comment by VladRassokhin** [comment]
AFAIR, back then @gregsh had some performance concerns how injector and editor would behave on large .bnf files with many injections.
Though I've not tested performance.

**Comment by ArtsiomCh** [comment]
Just made quick research. Created new .bnf file and copy and past few hundreds of time tokens below. There is **no visible difference** in opening that file with and without regexp injection, even on my old 2009 laptop.
```
{  tokens = [
    space='regexp:\s+'
    id="regexp:\w+"
    string="regexp:('([^'\\]|\\.)*'|\"([^\"\\]|\\\"|\\\'|\\)*\")"
    number="regexp:\d+"
    line_comment="regexp://.*"
    block_comment="regexp:/\*(.|\n)*\*/"
  ]
}
```
I also think people who search for ultimate performance are using VIM. Those who using IDEA are looking for  maximum support from the IDE. Escpecially in dealing with regexp, where it's so easy to made a mistake and so hard to find it later... It's worth to wait even few more second while everything loaded instead of waste few hours of searching bug.

PS  IMHO it's a huge difference in readability:
screenshot from 2017-11-26 15-42-31 crop
screenshot from 2017-11-26 15-42-31 crop regexp

**Comment by gregsh** [comment]
Thanks, @VladRassokhin, I've applied your changes more or less as is.
Just added `grammar.kit.inject.regexp` VM option to turn the injector off.

**Comment by ivanstepanovftw** [comment]
I think there is invalid warning message in my token `STRING_LITERAL    = "regexp:\"([^\"\\]|\\.)*\""`
```
Redundant character escape '\"' in RegExp
```

**Comment by VladRassokhin** [comment]
@iasemenov if so, please open new issue.

**Pull request closed without merging**
